name: Prepare readme's

on: workflow_dispatch

jobs:
  simple_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ryohidaka/action-md-insert@v1.2.0
        with:
          template_path: "./pack/template.md"
          src_dir: "./docs"
          dest_file: "./output.md"
