name: Prepare readme's

on: workflow_dispatch

jobs:
  simple_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown insert
        uses: ryohidaka/action-md-insert@v1.2.0
        with:
          template_path: "./pack/template.md"
          src_dir: "./docs"
          dest_file: ./output.md
      - name: Store readme
        uses: actions/upload-artifact@v3
        with:
          name: NPM md file
          path: pack/output.md
