name: Prepare readme's

on: workflow_dispatch

permissions:
  actions: write

jobs:
  simple_template:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v3
      with: 
        clean: false

    - name: Change permissions
      run: |
        sudo chmod -R 777 pack/
        
    - name: Insert markdown
      uses: ryohidaka/action-md-insert@v1.2.0
      with:
        template_path: "./pack/template.md"
        src_dir: "./docs"
        dest_file: pack/output.md
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: result-artifact
        path: pack/output.md
