name: Prepare readme's

on: workflow_dispatch

jobs:
  simple_template:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v3
      with: 
        clean: true

    # - name: Change permissions
    #  run: |
    #    sudo chmod -R 777 pack/
        
    # - name: Prepare NPM readme
    #  uses: ryohidaka/action-md-insert@v1.2.0
    #  with:
    #    template_path: "./docs/main.md"
    #    src_dir: "./"
    #    dest_file: readme.md
        
    # - name: Upload artifact
    # uses: actions/upload-artifact@v3
    # with:
    #   name: outputA
    #   path: readme.md

    - name: Prepare GitHub readme
      uses: ryohidaka/action-md-insert@v1.2.0
      with:
        template_path: "./docs/main.md"
        src_dir: "./docs"
        dest_file: readme.md
        
    - name: Commit updated readme
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto update readme.md
        file_pattern: '*.md'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: readme.md
